In [110]:
import pandas as pd

df = pd.read_csv("data_raw.csv")

In [111]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0 out of 5 stars,1,100+ bought in past month,195.99,basic variant price: nan,No Discount,No Badge,Organic,No Coupon,NaN,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2 out of 5 stars,20,200+ bought in past month,89.99,basic variant price: $25.00 off coupon applied,No Discount,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3 out of 5 stars,57,50+ bought in past month,899.99,basic variant price: Lowest price in 30 days,"$1,099.99",Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7 out of 5 stars,"7,102",500+ bought in past month,10.39,basic variant price: nan,$15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4 out of 5 stars,75,50+ bought in past month,419.99,basic variant price: nan,$499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-30 19:56:33

In [112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  str
 1   rating                    41651 non-null  str
 2   number_of_reviews         41651 non-null  str
 3   bought_in_last_month      39458 non-null  str
 4   current/discounted_price  30926 non-null  str
 5   price_on_variant          42675 non-null  str
 6   listed_price              42675 non-null  str
 7   is_best_seller            42675 non-null  str
 8   is_sponsored              42675 non-null  str
 9   is_couponed               42675 non-null  str
 10  buy_box_availability      28022 non-null  str
 11  delivery_details          30955 non-null  str
 12  sustainability_badges     3408 non-null   str
 13  image_url                 42675 non-null  str
 14  product_url               40606 non-null  str
 15  collected_at              42675 non-null  str
dtypes: str(16)
memory usage: 5.2 MB

In [113]:
print(df.dtypes)

title                       str
rating                      str
number_of_reviews           str
bought_in_last_month        str
current/discounted_price    str
price_on_variant            str
listed_price                str
is_best_seller              str
is_sponsored                str
is_couponed                 str
buy_box_availability        str
delivery_details            str
sustainability_badges       str
image_url                   str
product_url                 str
collected_at                str
dtype: object

In [114]:
print(df.isnull().sum())

title                           0
rating                       1024
number_of_reviews            1024
bought_in_last_month         3217
current/discounted_price    11749
price_on_variant                0
listed_price                    0
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability        14653
delivery_details            11720
sustainability_badges       39267
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [115]:
print(df.duplicated().sum())

0

In [116]:
df = df.drop(['sustainability_badges'], axis=1)

In [117]:
df['buy_box_availability'] = df['buy_box_availability'].fillna("Unknown")
df['delivery_details'] = df['delivery_details'].fillna("Not Specified")

In [118]:
df['listed_price'] = (df['listed_price'].replace('[\$,]', '', regex=True))
df['listed_price'] = pd.to_numeric(df['listed_price'], errors='coerce')

In [119]:
df['current/discounted_price'] = (df['current/discounted_price'].replace('[\$,]', '', regex=True))
df['current/discounted_price'] = pd.to_numeric( df['current/discounted_price'], errors='coerce')

In [120]:
df['number_of_reviews'] = df['number_of_reviews'].replace(',', '', regex=True).astype(float)

In [121]:
df['rating'] = df['rating'].str.extract(r'(\d+\.?\d*)')
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [122]:
df['bought_in_last_month'] = df['bought_in_last_month'].str.extract(r'(\d+\.?\d*)')

In [123]:
df['rating'] = df['rating'].fillna(df['rating'].mean())
df['number_of_reviews'] = df['number_of_reviews'].fillna(0)

In [124]:
df['current/discounted_price'] = df['current/discounted_price'].fillna(df['listed_price'])

In [125]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     42675 non-null  str
 1   rating                    42675 non-null  float64
 2   number_of_reviews         42675 non-null  float64
 3   bought_in_last_month      32233 non-null  str
 4   current/discounted_price  30926 non-null  float64
 5   price_on_variant          42675 non-null  str
 6   listed_price              12311 non-null  float64
 7   is_best_seller            42675 non-null  str
 8   is_sponsored              42675 non-null  str
 9   is_couponed               42675 non-null  str
 10  buy_box_availability      42675 non-null  str
 11  delivery_details          42675 non-null  str
 12  image_url                 42675 non-null  str
 13  product_url               40606 non-null  str
 14  collected_at              42675 non-null  str
dtypes: float64(4), str(11)
memory usage: 4.9 MB

In [126]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300,89.68,basic variant price: 2.4GHz,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6,9.99,basic variant price: nan,15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2,314.00,basic variant price: nan,349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10,NaN,basic variant price: $162.24,NaN,Best Seller,Organic,No Coupon,Unknown,Not Specified,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10,NaN,basic variant price: $72.74,NaN,No Badge,Organic,No Coupon,Unknown,Not Specified,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1.0,100,195.99,basic variant price: nan,NaN,No Badge,Organic,No Coupon,Unknown,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",https://m.media-amazon.com/images/I/51KCB+egEs...,/Elgato-4K-Pro-Internal-Capture/dp/B0DLR3WQWR/...,2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20.0,200,89.99,basic variant price: $25.00 off coupon applied,NaN,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",https://m.media-amazon.com/images/I/51jV+o1LZE...,/Arlo-Essential-Spotlight-Camera-Surveillance/...,2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57.0,50,899.99,basic variant price: Lowest price in 30 days,1099.99,Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",https://m.media-amazon.com/images/I/71ySPkNLkG...,/GIGABYTE-FO32U2-32-3840x2160-240Hz-FreeSync-A...,2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102.0,500,10.39,basic variant price: nan,15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",https://m.media-amazon.com/images/I/411c0JFJ79...,/Monoprice-XLR-Male-4-Inch-Cable/dp/B001UJEKZ6...,2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75.0,50,419.99,basic variant price: nan,499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",https://m.media-amazon.com/images/I/71wTn+zoSr...,/Lorex-8-Channel-Security-Outdoor-Cameras/dp/B...,2025-08-30 19:56:33

In [127]:
print(df.isnull().sum())

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month        10442
current/discounted_price    11749
price_on_variant                0
listed_price                30364
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details                0
image_url                       0
product_url                  2069
collected_at                    0
dtype: int64

In [128]:
df = df.drop(['image_url', 'product_url'], axis=1)

In [129]:
df = df.drop_duplicates()

In [130]:
print(df.isnull().sum())

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month        10442
current/discounted_price    11749
price_on_variant                0
listed_price                30364
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details                0
collected_at                    0
dtype: int64

In [131]:
df['bought_in_last_month'] = df['bought_in_last_month'].fillna(0)

In [132]:
df['listed_price'] = df['listed_price'].fillna(df['current/discounted_price'])
df['current/discounted_price'] = df['current/discounted_price'].fillna(df['listed_price'])

In [133]:
print(df.isnull().sum())

title                           0
rating                          0
number_of_reviews               0
bought_in_last_month            0
current/discounted_price    11749
price_on_variant                0
listed_price                11749
is_best_seller                  0
is_sponsored                    0
is_couponed                     0
buy_box_availability            0
delivery_details                0
collected_at                    0
dtype: int64

In [134]:
import pandas as pd

# Remove currency symbols, commas, text
df['price_on_variant'] = df['price_on_variant'].str.replace(r'[^\d\.]', '', regex=True)

# Convert to numeric
df['price_on_variant'] = pd.to_numeric(df['price_on_variant'], errors='coerce')

In [135]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300,89.68,2.40,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6,9.99,NaN,15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2,314.00,NaN,349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10,NaN,162.24,NaN,Best Seller,Organic,No Coupon,Unknown,Not Specified,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10,NaN,72.74,NaN,No Badge,Organic,No Coupon,Unknown,Not Specified,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1.0,100,195.99,NaN,195.99,No Badge,Organic,No Coupon,Unknown,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20.0,200,89.99,25.00,89.99,No Badge,Organic,Save $25.00 with coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57.0,50,899.99,30.00,1099.99,Save 18%,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102.0,500,10.39,NaN,15.98,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75.0,50,419.99,NaN,499.99,No Badge,Organic,No Coupon,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",2025-08-30 19:56:33

In [136]:
df['listed_price'] = df['listed_price'].fillna(df['price_on_variant'])
df['current/discounted_price'] = df['current/discounted_price'].fillna(df['price_on_variant'])

In [137]:
df[['listed_price','current/discounted_price']].isna().sum()

listed_price                1998
current/discounted_price    1998
dtype: int64

In [138]:
df = df.dropna(subset=['listed_price','current/discounted_price'])

In [139]:
df = df.dropna(subset=['price_on_variant'])

In [140]:
print(df.isnull().sum())

title                       0
rating                      0
number_of_reviews           0
bought_in_last_month        0
current/discounted_price    0
price_on_variant            0
listed_price                0
is_best_seller              0
is_sponsored                0
is_couponed                 0
buy_box_availability        0
delivery_details            0
collected_at                0
dtype: int64

In [141]:
df.shape

(21298, 13)

In [142]:
df.info()

<class 'pandas.DataFrame'>
Index: 21298 entries, 0 to 42672
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   title                     21298 non-null  str
 1   rating                    21298 non-null  float64
 2   number_of_reviews         21298 non-null  float64
 3   bought_in_last_month      21298 non-null  object
 4   current/discounted_price  21298 non-null  float64
 5   price_on_variant          21298 non-null  float64
 6   listed_price              21298 non-null  float64
 7   is_best_seller            21298 non-null  str
 8   is_sponsored              21298 non-null  str
 9   is_couponed               21298 non-null  str
 10  buy_box_availability      21298 non-null  str
 11  delivery_details          21298 non-null  str
 12  collected_at              21298 non-null  str
dtypes: float64(5), object(1), str(7)
memory usage: 2.3+ MB

In [143]:
df['bought_in_last_month'] = pd.to_numeric(df['bought_in_last_month'], errors='coerce')
df['bought_in_last_month'] = df['bought_in_last_month'].fillna(0)

In [144]:
df['buy_box_availability'].value_counts()

buy_box_availability
Add to cart    11039
Unknown        10259
Name: count, dtype: int64

In [145]:
df['is_best_seller'].value_counts()

is_best_seller
No Badge             20428
Amazon's               348
Limited time deal      199
Best Seller            134
Save 18%                57
Save 17%                51
Ends in                 37
Save 12%                26
Save 9%                 14
Save 77%                 2
Save 30%                 2
Name: count, dtype: int64

In [146]:
df['is_sponsored'].value_counts()

is_sponsored
Organic      20461
Sponsored      837
Name: count, dtype: int64

In [147]:
df['is_couponed'].value_counts()

is_couponed
No Coupon                    20806
Save 10%  with coupon          171
Save $100.00  with coupon       97
Save $25.00  with coupon        65
Save $69.00  with coupon        31
Save $16.00  with coupon        26
Save 15%  with coupon           25
Save $33.00  with coupon        13
Save 20%  with coupon            6
Save $18.00  with coupon         5
Save $15.00  with coupon         5
Save $30.00  with coupon         5
Save $45.00  with coupon         5
Save 5%  with coupon             4
Save $10.00  with coupon         4
Save $11.00  with coupon         4
Save 40%  with coupon            4
Save $4.00  with coupon          3
Save $8.00  with coupon          2
Save $1.50  with coupon          2
Save $20.00  with coupon         2
Save $60.00  with coupon         2
Save $40.00  with coupon         1
Save $5.00  with coupon          1
Save $12.00  with coupon         1
Save $50.00  with coupon         1
Save 25%  with coupon            1
Save 30%  with coupon            1
Save $3.00  with coupon          1
Save $1.00  with coupon          1
Save 50%  with coupon            1
Save $120.00  with coupon        1
Save $90.00  with coupon         1
Name: count, dtype: int64

In [109]:
df

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,2.40,159.00,NaN,NaN,NaN,Add to cart,"Delivery Mon, Sep 1",2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6.0,9.99,NaN,15.99,NaN,NaN,NaN,Add to cart,"Delivery Fri, Aug 29",2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2.0,314.00,NaN,349.00,NaN,NaN,NaN,Add to cart,"Delivery Mon, Sep 1",2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10.0,162.24,162.24,162.24,NaN,NaN,NaN,Unknown,Not Specified,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10.0,72.74,72.74,72.74,NaN,NaN,NaN,Unknown,Not Specified,2025-08-21 11:14:29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1.0,100.0,195.99,NaN,195.99,NaN,NaN,NaN,Unknown,"FREE delivery Thu, Sep 4Or fastest delivery Tu...",2025-08-30 19:56:33
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20.0,200.0,89.99,25.00,89.99,NaN,NaN,NaN,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery Mo...",2025-08-30 19:56:33
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57.0,50.0,899.99,30.00,1099.99,NaN,NaN,NaN,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",2025-08-30 19:56:33
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102.0,500.0,10.39,NaN,15.98,NaN,NaN,NaN,Add to cart,"FREE delivery Thu, Sep 4 on $35 of items shipp...",2025-08-30 19:56:33
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75.0,50.0,419.99,NaN,499.99,NaN,NaN,NaN,Add to cart,"FREE delivery Thu, Sep 4Or fastest delivery We...",2025-08-30 19:56:33

In [148]:
df['is_best_seller_flag'] = df['is_best_seller'].str.contains('Best Seller', case=False).astype(int)

In [149]:
df['has_badge'] = (df['is_best_seller'] != 'No Badge').astype(int)

In [150]:
df = df.drop(columns=['is_best_seller'])

In [151]:
df['is_sponsored'] = df['is_sponsored'].map({
    'Organic': 0,
    'Sponsored': 1
})

In [152]:
df['has_coupon'] = (df['is_couponed'] != 'No Coupon').astype(int)

In [153]:
df['coupon_percent'] = df['is_couponed'].str.extract(r'(\d+)%')
df['coupon_percent'] = pd.to_numeric(df['coupon_percent'], errors='coerce')

In [154]:
df['coupon_value'] = df['is_couponed'].str.extract(r'\$(\d+\.?\d*)')
df['coupon_value'] = pd.to_numeric(df['coupon_value'], errors='coerce')

In [155]:
df['coupon_percent'] = df['coupon_percent'].fillna(0)
df['coupon_value'] = df['coupon_value'].fillna(0)

In [156]:
df = df.drop(columns=['is_couponed'])

In [161]:
df.info()

<class 'pandas.DataFrame'>
Index: 21298 entries, 0 to 42672
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   rating                    21298 non-null  float64
 1   number_of_reviews         21298 non-null  float64
 2   bought_in_last_month      21298 non-null  float64
 3   current/discounted_price  21298 non-null  float64
 4   price_on_variant          21298 non-null  float64
 5   listed_price              21298 non-null  float64
 6   is_sponsored              21298 non-null  int64
 7   buy_box_availability      21298 non-null  int64
 8   collected_at              21298 non-null  str
 9   is_best_seller_flag       21298 non-null  int64
 10  has_badge                 21298 non-null  int64
 11  has_coupon                21298 non-null  int64
 12  coupon_percent            21298 non-null  float64
 13  coupon_value              21298 non-null  float64
dtypes: float64(8), int64(5), str(1)
memory usage: 2.4 MB

In [158]:
df = df.drop(columns=[
    'title',              # text
    'delivery_details',   # text
 ])

In [165]:
df = df.drop(columns=['collected_at'])

In [159]:
df['buy_box_availability'].value_counts()

buy_box_availability
Add to cart    11039
Unknown        10259
Name: count, dtype: int64

In [160]:
df['buy_box_availability'] = df['buy_box_availability'].map({'Add to cart':1,'Unknown':0})

In [162]:
df = df.drop(columns=['price_on_variant'])

In [163]:
df['final_price'] = df['current/discounted_price']

df['discount_percentage'] = (
    (df['listed_price'] - df['current/discounted_price']) 
    / df['listed_price']
) * 100

In [167]:
df = df.drop(columns=[
    'listed_price',
    'current/discounted_price',

])

In [168]:
features = df[[
    'final_price',
    'discount_percentage',
    'rating',
    'number_of_reviews',
    'bought_in_last_month',
    'is_sponsored',
    'buy_box_availability',
    'is_best_seller_flag',
    'has_badge',
    'has_coupon',
    'coupon_percent',
    'coupon_value'
]]

In [170]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

In [171]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

In [172]:
df['rating_category'] = pd.cut(df['rating'],bins=[0, 3.5, 4.5, 5],labels=['Low', 'Medium', 'High'])

In [175]:
df['price_category'] = pd.cut(df['final_price'],bins=3,labels=['Cheap', 'Moderate', 'Expensive']
)

In [174]:
df['rating_category'].value_counts()

rating_category
Medium    12512
High       8127
Low         659
Name: count, dtype: int64

In [176]:
df['price_category'].value_counts()

price_category
Cheap        20745
Moderate       340
Expensive      213
Name: count, dtype: int64

In [178]:
df['PC1'] = X_pca[:, 0]
df['PC2'] = X_pca[:, 1]

In [179]:
df

,rating,number_of_reviews,bought_in_last_month,is_sponsored,buy_box_availability,is_best_seller_flag,has_badge,has_coupon,coupon_percent,coupon_value,final_price,discount_percentage,rating_category,price_category,PC1,PC2
0,4.6,375.0,300.0,1,1,0,0,1,15.0,0.0,89.68,43.597484,High,Cheap,11.429296,0.206467
3,4.6,35882.0,10.0,0,0,1,1,0,0.0,0.0,162.24,0.000000,High,Cheap,0.902149,-4.834531
4,4.8,28988.0,10.0,0,0,0,0,0,0.0,0.0,72.74,0.000000,High,Cheap,-0.604250,-0.057650
5,4.6,44522.0,100.0,0,0,1,1,0,0.0,0.0,99.95,0.000000,High,Cheap,0.983963,-5.185870
6,4.5,13466.0,10.0,0,0,0,0,0,0.0,0.0,88.11,0.000000,Medium,Cheap,-0.696206,0.423502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42657,4.4,2031.0,100.0,0,1,0,0,0,0.0,0.0,282.04,0.000000,Medium,Cheap,-0.039113,-0.075123
42658,4.5,2877.0,400.0,0,1,0,0,0,0.0,0.0,19.94,13.266638,Medium,Cheap,0.394008,-1.339328
42665,4.9,19.0,300.0,0,0,0,0,0,0.0,0.0,126.70,0.000000,High,Cheap,-0.437860,-0.090667
42671,4.2,20.0,200.0,0,1,0,0,1,0.0,25.0,89.99,0.000000,Medium,Cheap,5.508548,2.649426
42672,4.3,57.0,50.0,0,1,0,1,0,0.0,0.0,899.99,18.181983,Medium,Cheap,0.791001,-1.738010